### ISSUE TITLE
pybuild is failing

### ISSUE THREAD

**Issue by alvesadrian** [glenfant/stopit#11]
I: pybuild base:184: /usr/bin/python3 setup.py build 
running build
running build_py
creating /tmp/b/a/stopit/.pybuild/pythonX.Y_3.5/build/stopit
copying src/stopit/**init**.py -> /tmp/b/a/stopit/.pybuild/pythonX.Y_3.5/build/stopit
copying src/stopit/signalstop.py -> /tmp/b/a/stopit/.pybuild/pythonX.Y_3.5/build/stopit
copying src/stopit/utils.py -> /tmp/b/a/stopit/.pybuild/pythonX.Y_3.5/build/stopit
copying src/stopit/threadstop.py -> /tmp/b/a/stopit/.pybuild/pythonX.Y_3.5/build/stopit
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:184: cd /tmp/b/a/stopit/.pybuild/pythonX.Y_2.7/build; python2.7 -m pytest 
============================= test session starts ==============================
platform linux2 -- Python 2.7.11+, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /tmp/b/a/stopit, inifile: 
collected 0 items

========================= no tests ran in 0.00 seconds =========================
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=5: cd /tmp/b/a/stopit/.pybuild/pythonX.Y_2.7/build; python2.7 -m pytest 
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 2.7 --dir . returned exit code 13
debian/rules:4: recipe for target 'build' failed
make: **\* [build] Error 25
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:

**Comment by glenfant** [comment]
Hi @alvesadrian ,
I'm not familiar with Debian style packaging, in fact I'm working with a MacOS laptop. With more background, and detailed informations, I could try to reproduce the issue in a Debian Vagrant box.

Ah, and the provided tests use the standard "doctest" package and **not** the "pytest" framework.

**Comment by glenfant** [comment]
I confirm: with whatever Python version within 2.7 and 3.5, under Mac OSX and a Debian Vagrant box, I have the same result :

```
$ python tests.py 
README.rst
Doctest: README.rst ... ok
README.rst
Doctest: README.rst ... ok

----------------------------------------------------------------------
Ran 2 tests in 16.743s

OK
```

**Comment by glenfant** [comment]
@alvesadrian  Ah ! Tests are driven by stdlib "doctests", and not with third party "pytest".

See https://github.com/glenfant/stopit/blob/master/tests.py

Fix your packaging options.
