### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by frol** [glenfant/stopit#14]
Could you, please, consider using a less restrictive license, e.g. MIT?

**Comment by glenfant** [comment]
What's the issue with your usage of stopit ?

**Comment by frol** [comment]
I wanted to use it in a closed-source project, so GPL license (which stopit is licensed with) would be a show stopper. In any case, I have already realized that neither signal-based nor threaded implementations fit my use-case (I need an accurate and Windows-compatible solution, but there is simply no way to achieve that, so I will redesign my implementation to be cooperative instead of aggressive)

**Comment by peterjc** [comment]
See f32f1b60a6c5a1febad892d9004f6397c93d790a - now MIT licensed.
