### ISSUE TITLE
TimeoutException is not raised if using subprocess

### ISSUE THREAD

**Issue by azastupailo** [glenfant/stopit#16]
I'm using Tesseract as OCR engine to process some documents. However, I would like to restrict the time of execution for tesseract process max to 5 mins. 

The problem is that the code below sometimes kills the process properly after 5 mins, but sometimes I see a slowdown in the system due to tesseract process running for much longer.
For example, today I've noticed in logs that it took 37 minutes between `Will run OCR...` and `Tesseract timed out. Killing the ocr process ...`  (`Code block execution exceeded 300 seconds timeout` internal `stopit` log message).

```python
try:
    with stopit.ThreadingTimeout(300, swallow_exc=False):
        logger.info('Will run OCR...')

        command = 'tesseract {} {} --psm 1 -l eng hocr'.format(image_path, hocr_file_path).split()
        ocr_process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        # Wait for the tesseract process to finish and fetch stdout/stderr
        stdout, stderr = self.ocr_process.communicate()

        # ...
        # Do some processing of results
except stopit.utils.TimeoutException:
    logger.exception('Tesseract timed out. Killing the ocr process ...')
    ocr_process.kill()
    # ...
```

Can you help me please to understand if I'm using `stopit` for the wrong scenario or what can be the problem?

**Comment by glenfant** [comment]
HI @azastupailo , you hit another limitation of stopit I didn't mention in the doc, and you made a mistake in your code. stopit ignores and cannot control (kill) a subprocess. You should use the timeout optional parameter of the `communicate()` method of Popen objects.

https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate

**Comment by azastupailo** [comment]
Hi @glenfant , thank you for taking a look at the issue so fast. Also, good catch with a timeout parameter! I'll try to implement and test fixes in a couple of days and will update the issue so that maybe it will save some time for somebody else.

**Comment by glenfant** [comment]
The README writes that the ThreadingTimeout CM "Can't interrupt a long Python atomic instruction. e.g. if time.sleep(20.0) is actually executing, the timeout will take effect at the end of the execution of this line.". That's what happened. The TimeoutException is in effect AFTER the end of call of `communicate()` call because this took more than 5 minutes.

**Comment by glenfant** [comment]
Note that the new `asyncio` based subprocesses control provides a clean way to manage timeout in subprocesses too.

**Comment by azastupailo** [comment]
@glenfant thank you for your suggestions again. For now we sticked with the `timeout` parameter in `communicate()` method as it does the job in our case and it was a quick change. However, we'll consider `asyncio` too for our scenario.

We migrated recently from Python 2 to 3 and `timeout` was introduced in Python 3 which we somehow missed.

Anyways, thank you for this library and your support.
