### ISSUE TITLE
threading locks and stopit

### ISSUE THREAD

**Issue by andresriancho** [glenfant/stopit#6]
I've added stopit to the [w3af](https://github.com/andresriancho/w3af/tree/feature/stopit) framework with the objective of killing document parsers (w3af is a crawler with security features) which take more than N seconds to parse an HTTP response body.

While running some test scans I've noticed (but not yet confirmed 100%) that in some cases all the threads are dead-locked waiting for a threading.RLock to be released:

```
w3af-10287-2015-05-01-05_26.threads:        "  File \"parser_cache.py\", line 84, in get_document_parser_for\n    with self._LRULock:\n", 
w3af-10287-2015-05-01-05_26.threads:        "  File \"parser_cache.py\", line 84, in get_document_parser_for\n    with self._LRULock:\n", 
...
w3af-10287-2015-05-01-05_26.threads:        "  File \"parser_cache.py\", line 84, in get_document_parser_for\n    with self._LRULock:\n", 
```

This output is generated by [this thread traceback dump script](https://github.com/andresriancho/w3af/blob/feature/stopit/w3af/core/controllers/profiling/thread_activity.py) which hasn't failed for me in the past. When the framework parser cache is working as expected the output looks like:

```
w3af-10287-2015-05-01-05_19.threads:        "  File \"parser_cache.py\", line 84, in get_document_parser_for\n    with self._LRULock:\n", 
w3af-10287-2015-05-01-05_19.threads:        "  File \"parser_cache.py\", line 90, in get_document_parser_for\n    res = DocumentParser.DocumentParser(http_response)\n", 
w3af-10287-2015-05-01-05_19.threads:        "  File \"parser_cache.py\", line 84, in get_document_parser_for\n    with self._LRULock:\n", 
```

The pseudo-code for the code I'm having problems with is:

``` python
with self._LRULock:
    try:
        with ThreadingTimeout(self.PARSER_TIMEOUT, swallow_exc=False):
            self._parser = parser(http_resp)
    except TimeoutException:
        logging.debug(...)
```

I know that the timeout is being triggered because the debug message appears in the logs.

The question is... is there any known bug with `stopit` , `PyThreadState_SetAsyncExc` and threading locks?

I've tried to reproduce this issue in [this commit](https://github.com/andresriancho/w3af/commit/46623043c1288963835a8f5bc83f9d366e1e9f19) but all seems to be working as expected.

**Comment by glenfant** [comment]
Hi @andresriancho 

There are known issues (not really bugs) in stopit du to the nature of the threading model of the CPython interpreter. These known issues are clearly (hopefully) explained in the README.

If I understand clearly your issue, when the inner "with" block is terminated by a timeout, the lock (self._LRULock) is never released when it should be when leaving the outer "with" block.

I have to admit anyay I didn't test  stopit in complex threading situation.

Could you initiate a fork of stopit with an unit test that triggers this issue ?

**Comment by glenfant** [comment]
@andresriancho : something else comes in mind : does your code block under timeout control call subprocesses ?

**Comment by andresriancho** [comment]
> There are known issues (not really bugs) in stopit du to the nature of the threading model of the CPython interpreter. These known issues are clearly (hopefully) explained in the README.

Well, the readme helps a lot (mostly the table that compares signals and threads) but I had to read several other sources to really understand what could go wrong.

> If I understand clearly your issue, when the inner "with" block is terminated by a timeout, the lock (self._LRULock) is never released when it should be when leaving the outer "with" block.

Yes, that's the problem.

> Could you initiate a fork of stopit with an unit test that triggers this issue ?

I actually tried to reproduce it and failed, I'm pretty sure it's an issue but haven't been able to reproduce in a minimalistic example.

> something else comes in mind : does your code block under timeout control call subprocesses ?

Not that I know of. You thinking about zombie processes?

**Comment by glenfant** [comment]
This is somehow ugly :o) but could you try something like this instead of your actual code snippet and inspect what is logged ?

```python
try:
    self._LRULock.acquire()  # Assuming this is a 'threading.Lock' object
    try:
        with ThreadingTimeout(self.PARSER_TIMEOUT, swallow_exc=False) as tocm:
            self._parser = parser(http_resp)
    except TimeoutException:
        logging.debug(...)
finally:
    logging.debug("Will release lock, timeout status is %d", tocm.state)
    self._LRULock.release()
    logging.debug("Lock released")
```
I was asking a stupid question about subprocesses ;o)

Don't hesitate to continue this ticket if you can provide a short example that triggers this issue. If it's not possible to fix, I could add an item in the FAQ of the README file.

Good luck and thanks to help me to provide a better "stopit".

**Comment by glenfant** [comment]
Forgit to kick @andresriancho  :o)

**Comment by glenfant** [comment]
Hi @andresriancho ,

Did you manage making a test that show that issue or should I close it ?

**Comment by andresriancho** [comment]
No, sorry, I did try to reproduce it in a simple test as shown here https://github.com/andresriancho/w3af/commit/46623043c1288963835a8f5bc83f9d366e1e9f19 , but that worked and the reality (with many threads) did not.

Not sure what was wrong: your code or mine.

Feel free to close this issue if you feel like it was my code, or leave it open in case you want to write the test(s) and try to reproduce yourself.

From my point of view there is a 50/50 chance..., I'm not inclined in blaming #stopit for this :+1:

**Comment by glenfant** [comment]
@andresriancho : Cannot reproduce this with a unit test. Closing the issue. You may re-open it if you provide a fork with a test that shows the issue.

**Comment by andresriancho** [comment]
We stopped using stopit in w3af.
