### ISSUE TITLE
Why does this stopit code fail?

### ISSUE THREAD

**Issue by VeereshElango** [glenfant/stopit#7]
I am facing a strange issue with the stopit module. The below code works fine:
```
import stopit

def check(num):
    with stopit.ThreadingTimeout(3) as to_ctx_mrg:
        count = 0
        while(True):

            if False:
                continue    

    if to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
            print(to_ctx_mrg.state)
            print("Time out")
            raise TimeoutError

try:
    check(1)
except TimeoutError:
    print("Caught the timeout")
```
But, when I change the if condition slightly, stopit is not able to recognize this infinite loop and the program does not stop. Take a look at the modified code:
```
import stopit

def check(num):
    with stopit.ThreadingTimeout(3) as to_ctx_mrg:
        count = 0
        while(True):

            if num>31:
                continue    

    if to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
            print(to_ctx_mrg.state)
            print("Time out")
            raise TimeoutError

try:
    check(1)
except TimeoutError:
    print("Caught the timeout")
```

**Comment by glenfant** [comment]
@VeereshElango 

There is no `TimeoutError` in the Python global namespace. But there is a `stopit.TimeoutException` you may re-use for your own purposes. If you want to use your custom `TimeoutError` exception, you should define it **before** using it as any other Python custom object. This one works as expected.

```python
import stopit

# My 2 lines add
class TimeoutError(Exception):
    pass

# This is unchanged
def check(num):
    with stopit.ThreadingTimeout(3) as to_ctx_mrg:
        count = 0
        while(True):

            if num>31:
                continue

    if to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
            print(to_ctx_mrg.state)
            print("Time out")
            raise TimeoutError

try:
    check(1)
except TimeoutError:
    print("Caught the timeout")
```

**Comment by Deepak-Mahalingam** [comment]
Hi glenfant,
Even I faced a similar issue. Please take a look at the below code, which works fine:
    
    
    import stopit
    def check(num):
        with stopit.ThreadingTimeout(3) as to_ctx_mrg:
            while(True):
                if num>0:
                    continue    
    
        if to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
                print(to_ctx_mrg.state)
                print("Time out")
                
    check(1)

But when I change the `if` condition inside the loop, stopit does not work. Take a look at the modified code:

    
    import stopit
    def check(num):
        with stopit.ThreadingTimeout(3) as to_ctx_mrg:
            while(True):
                if num<0:
                    continue    
    
        if to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
                print(to_ctx_mrg.state)
                print("Time out")
                
    check(1)

**Comment by glenfant** [comment]
@Deepak-Mahalingam Could you please be more specific ? Your two scripts work as expected with Python 2.7, 3.3 and 3.4 on my Macbook. In all 4 cases, it prints after 3 seconds : 
```
2
Time out
```
What's your system, your Python version ?

**Comment by Deepak-Mahalingam** [comment]
@glenfant I am using Windows 7, 32 bit . Python 3.4.3. The first script works fine and prints the output as expected. But the second script goes into an infinite loop and the program neither prints an output nor it terminates.

**Comment by glenfant** [comment]
@Deepak-Mahalingam : I'm sorry, I have no Windows box or such to test this. Could you provide a Vagrantfile in a gist that sets up a Windows environment that shows this issue ?

Otherwise try this code

```python
import stopit

def check(num):
    try:
        with stopit.ThreadingTimeout(3) as to_ctx_mrg:
            while(True):
                if num<0:
                    continue
    except KeyboardInterrupt:
        print(to_ctx_mrg.state)


check(1)
```
Wait more than 3 seconds then hit Ctrl-C and tell me what it prints.
